In [1]:
import numpy as np

In [3]:
my_list = [-1,0,1]
my_list

[-1, 0, 1]

In [5]:
my_array= np.array(my_list)
my_array

array([-1,  0,  1])

In [7]:
type(my_array)

numpy.ndarray

In [9]:
my_matrix= [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [11]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
matrix_one.shape


(2, 3)

Now will be start all the basics of np


In [16]:
num= np.arange(100) #similer to range(),not including 100
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.arange(3,10,2) #from 3 to till 9 incriment 2

array([3, 5, 7, 9])

In [20]:
np.arange(3,10,2, dtype=float)  #data will be all in float

array([3., 5., 7., 9.])

linspace() 

In [23]:
np.linspace(1,100,1000, retstep=True) #form 1 to 100 divided into 1000, retstep for the difference or bhag e koto kore pore 


(array([  1.        ,   1.0990991 ,   1.1981982 ,   1.2972973 ,
          1.3963964 ,   1.4954955 ,   1.59459459,   1.69369369,
          1.79279279,   1.89189189,   1.99099099,   2.09009009,
          2.18918919,   2.28828829,   2.38738739,   2.48648649,
          2.58558559,   2.68468468,   2.78378378,   2.88288288,
          2.98198198,   3.08108108,   3.18018018,   3.27927928,
          3.37837838,   3.47747748,   3.57657658,   3.67567568,
          3.77477477,   3.87387387,   3.97297297,   4.07207207,
          4.17117117,   4.27027027,   4.36936937,   4.46846847,
          4.56756757,   4.66666667,   4.76576577,   4.86486486,
          4.96396396,   5.06306306,   5.16216216,   5.26126126,
          5.36036036,   5.45945946,   5.55855856,   5.65765766,
          5.75675676,   5.85585586,   5.95495495,   6.05405405,
          6.15315315,   6.25225225,   6.35135135,   6.45045045,
          6.54954955,   6.64864865,   6.74774775,   6.84684685,
          6.94594595,   7.04504505,   7.

In [25]:
np.linspace(1,15,30, retstep=True)

(array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
         3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
         5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
         8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
        10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
        13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ]),
 0.4827586206896552)

Use all this function till now

In [28]:
x=np.arange(0,16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
x.shape


(16,)

In [32]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
y=x.reshape(4,2,2)  #Means 4 matrix which have 2 row and 2 column 
y

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [36]:
x=y.reshape(16,)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
np.random.rand(5)  #1-d array--- range of rand 0 to 1.

array([0.56941627, 0.46907501, 0.75993969, 0.77218072, 0.189211  ])

In [48]:
np.random.rand(6,4)   #6,4 is the array size which is 2-D

array([[0.1802571 , 0.61734733, 0.7200891 , 0.99968592],
       [0.39045723, 0.1903917 , 0.09879803, 0.29195039],
       [0.05334092, 0.42149065, 0.52878966, 0.26549149],
       [0.56402489, 0.33177524, 0.27690359, 0.44131773],
       [0.97378555, 0.90779991, 0.55554517, 0.57980002],
       [0.5566074 , 0.6497069 , 0.0722823 , 0.68078123]])

In [52]:
np.random.randint(1,50,16).reshape(4,4)  #means will give 16 output from 1 to 50 

array([[21, 34, 27, 44],
       [38, 23, 16,  2],
       [18, 40, 29, 26],
       [38,  1,  1, 43]])

In [58]:
randomint= np.random.randint(1,50,16)
randomint

array([34, 29,  1, 49, 17, 33, 18, 10, 14, 24,  3, 47, 31, 21,  5,  8])

In [64]:
randomint.min()


1

In [66]:
randomint.max()

49

In [70]:
randomint.argmax()  #Returns the index number in the array

3